# Generated by Django 6.0.5 on 2026-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinquiry",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="contactinquiry",
            name="topic",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
