# Generated by Django 5.0.2 on 2025-12-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, help_text='CSS class name for service icon', max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which services are displayed (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is currently active and displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
